version: "3"

tasks:
  preview_openapi:
    desc: "Preview the OpenAPI spec using Swagger UI"
    cmds:
      - |
        docker run \
          --rm \
          -p 7000:8080 \
          -e SWAGGER_JSON=/openapi.yaml \
          -v $(pwd)/docs/openapi.yaml:/openapi.yaml \
          swaggerapi/swagger-ui
    silent: true
