- name: 🐔 New Feature
  description: New feature
  color: 6E05F7
- name: 🐛 Bug
  description: Something isn't working
  color: FA8286
- name: ✨ Refactoring
  description: Improve readability without changing behavior
  color: F5E10A
- name: 🤖 Automation
  description: Eliminate the toile
  color: 0A7FF5
- name: 🔧 Improvement
  description: Include anything from improving the development environment to improving the UX
  color: 4C9DED
- name: 🔥 Priority/High
  description: Priority is High
  color: FF0000
- name: 💧 Priority/Low
  description: Priority is Low
  color: 0000FF
- name: 🕸️ Web
  description: web side issue
  color: FFFFFF
- name: 🐶 Backend
  description: backend side issue
  color: FFFFFF
