[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
# axum = "0.6.18"
# tokio = { version = "1.28.0", features = ["full"] }
# serde = { version = "1.0.162", features = ["derive"] }

# uuid = { version = "1.3.2", features = ["serde", "v4"] }

# anyhow = "1.0.71"
