[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Web framework
axum = "0.6.20"
tokio = { version = "1.32.0", features = ["full"] }

# For dotenv
dotenvy = "0.15.7"

# serde = { version = "1.0.162", features = ["derive"] }
# uuid = { version = "1.3.2", features = ["serde", "v4"] }
# anyhow = "1.0.71"
