version: "3.8"
services:
  db:
    # https://www.cockroachlabs.com/docs/v23.1/start-a-local-cluster-in-docker-mac#start-a-single-node-cluster
    container_name: shamo-backend-db
    image: cockroachdb/cockroach:v23.1.10
    ports:
      - 26257:26257
      - 8081:8080
    command: start-single-node
    environment:
      - COCKROACH_USER=username
      - COCKROACH_PASSWORD=password
    volumes:
      - type: volume
        source: db
        target: /cockroach/cockroach-data
        volume:
          nocopy: true
      - type: bind
        source: ./docker/cockroach/certs
        target: /cockroach/certs
        bind:
          # Configuration to create `certs` directories created on the container side on the host side.
          # https://docs.docker.com/compose/compose-file/05-services/#long-syntax-5
          create_host_path: true
      - type: bind
        source: ./docker/cockroach/init
        target: /docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
