version: "3.8"
services:
  db:
    # https://www.cockroachlabs.com/docs/v23.1/start-a-local-cluster-in-docker-mac#start-a-single-node-cluster
    container_name: shamo-backend-db
    image: cockroachdb/cockroach:v23.1.10
    ports:
      - 26257:26257
      - 8081:8080
    command: start-single-node --insecure
    volumes:
      - type: volume
        source: db
        target: /cockroach/cockroach-data
        volume:
          nocopy: true
      - type: bind
        source: ./docker/db/init
        target: /docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
