[config]
# There are rich features that support workspace. I don't use it, so I disable it; if enabled, I get an error.
# https://github.com/sagiegurari/cargo-make#disabling-workspace-support
default_to_workspace = false
# Do not load default tasks
# https://github.com/sagiegurari/cargo-make#disabling-predefined-tasksflows
skip_core_tasks = true

[tasks.run-middleware]
script = 'docker compose up -d'

[tasks.run]
script = 'ENV=development cargo watch -x run'
dependencies = [
  "run-middleware"
]

[tasks.in-db]
script = 'docker exec -it shamo-backend-db ./cockroach sql --url="postgresql://127.0.0.1:26257/shamo?user=root&sslmode=disable"'

[tasks.test]
script = 'ENV=test cargo test --workspace'

[tasks.docker-build]
script = 'docker build --build-arg ENV=development -t shamo-backend .'

# 以下のエラーがでるのでつかえませんな〜
# root@88ad1ea81995:/app# psqldef -h host.docker.internal -p ${PGPORT} -U ${PGUSER} -W ${PGPASSWORD} ${PGDATABASE} --export
# 2023/10/07 10:58:57 Error on DumpDDLs: sql: Scan error on column index 0, name "column_name": converting NULL to string is unsupported
[tasks.db-migration]
script = "docker build -t shamo-backend-psqldef-executor -f Dockerfile.sqldef . && docker run --env-file .env.development --rm shamo-backend-psqldef-executor"

# [tasks.setup-local]
# dependencies = [
#   "db-migration-local"
# ]
