name = "shamo-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
workers_dev = false
routes = [
  { pattern = "shamo-api.mi-wada.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "shamo-api-db"
database_id = "8c1cce3c-92e0-4251-a44f-c40f6591eee3"

[observability]
enabled = true

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
