openapi: 3.0.0
info:
  title: Shamo 🐔 API
  version: 1.0.0
paths:
  /rooms:
    $ref: './paths/rooms.yml'
  /rooms/{room_id}:
    $ref: './paths/rooms_{room_id}.yml'
  /rooms/{room_id}/payments:
    $ref: './paths/rooms_{room_id}_payments.yml'
  /rooms/{room_id}/payments/{payment_id}:
    $ref: './paths/rooms_{room_id}_payments_{payment_id}.yml'
