name: backend / Test
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/**'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/**'
defaults:
  run:
    working-directory: ./backend
permissions:
  contents: read
  pull-requests: write
jobs:
  test:
    env:
      CARGO_INCREMENTAL: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # For git-restore-mtime-action in .github/actions/backend-setup-rust
          fetch-depth: 0
      - uses: ./.github/actions/backend-setup-rust
      - run: docker compose up -d
      - run: cargo test --workspace
