name: infra / Lint
on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/**'
  pull_request:
    paths:
      - 'infra/**'
      - '.github/**'
defaults:
  run:
    working-directory: ./infra
permissions:
  contents: read
  pull-requests: write
jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    # TODO: 消したい
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - name: Get Terraform version
        id: tf_version
        run: echo ::set-output name=version::$(cat .terraform-version)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.version }}
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Terraform Validate
        run: terraform validate
# TODO: Add tflint
