name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/sync_labels.yml
permissions:
  issues: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
          # https://github.com/micnncim/action-label-syncer/blob/3abd5ab72fda571e69fffd97bd4e0033dd5f495c/action.yml#L15-L18
          prune: true
